/* eslint-disable */
/*Generated by GenDocu.com*/
// package: relay.notification.v1.channels.webhook
// file: relay/notification/v1/channels/webhook.proto

import * as jspb from "google-protobuf";

export class GetResponseData extends jspb.Message {
  getUrl(): string;
  setUrl(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): GetResponseData.AsObject;
  static toObject(includeInstance: boolean, msg: GetResponseData): GetResponseData.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: GetResponseData, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): GetResponseData;
  static deserializeBinaryFromReader(message: GetResponseData, reader: jspb.BinaryReader): GetResponseData;
}

export namespace GetResponseData {
  export type AsObject = {
    url: string,
  }
}

