/* eslint-disable */
/*Generated by GenDocu.com*/
// source: relay/onboarding/v1/payment_method_onboarding_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var relay_models_pb = require('../../../relay/models_pb.js');
goog.object.extend(proto, relay_models_pb);
var relay_onboarding_v1_paymentmethods_ppro_pb = require('../../../relay/onboarding/v1/paymentmethods/ppro_pb.js');
goog.object.extend(proto, relay_onboarding_v1_paymentmethods_ppro_pb);
goog.exportSymbol('proto.relay.onboarding.v1.CompletelyNew', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.CompletelyNew.PaymentselectionCase', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.GetRequest', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.GetResponse', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.InitializeRequest', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.InitializeResponse', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.NewIndeed', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.PaymentMethodOnboardingStatus', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.ResNested', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.TryNested', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.UpdateRequest', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.UpdateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.TryNested = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.TryNested, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.TryNested.displayName = 'proto.relay.onboarding.v1.TryNested';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.ResNested = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.ResNested, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.ResNested.displayName = 'proto.relay.onboarding.v1.ResNested';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.CompletelyNew = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_);
};
goog.inherits(proto.relay.onboarding.v1.CompletelyNew, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.CompletelyNew.displayName = 'proto.relay.onboarding.v1.CompletelyNew';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.NewIndeed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.NewIndeed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.NewIndeed.displayName = 'proto.relay.onboarding.v1.NewIndeed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.InitializeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.InitializeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.InitializeRequest.displayName = 'proto.relay.onboarding.v1.InitializeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.InitializeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.InitializeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.InitializeResponse.displayName = 'proto.relay.onboarding.v1.InitializeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.UpdateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.UpdateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.UpdateRequest.displayName = 'proto.relay.onboarding.v1.UpdateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.UpdateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.UpdateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.UpdateResponse.displayName = 'proto.relay.onboarding.v1.UpdateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.GetRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.GetRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.GetRequest.displayName = 'proto.relay.onboarding.v1.GetRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.GetResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.GetResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.GetResponse.displayName = 'proto.relay.onboarding.v1.GetResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.TryNested.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.TryNested.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.TryNested} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.TryNested.toObject = function(includeInstance, msg) {
  var f, obj = {
    sthg: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.TryNested}
 */
proto.relay.onboarding.v1.TryNested.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.TryNested;
  return proto.relay.onboarding.v1.TryNested.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.TryNested} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.TryNested}
 */
proto.relay.onboarding.v1.TryNested.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSthg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.TryNested.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.TryNested.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.TryNested} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.TryNested.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSthg();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string Sthg = 1;
 * @return {string}
 */
proto.relay.onboarding.v1.TryNested.prototype.getSthg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.TryNested} returns this
 */
proto.relay.onboarding.v1.TryNested.prototype.setSthg = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.ResNested.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.ResNested.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.ResNested} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.ResNested.toObject = function(includeInstance, msg) {
  var f, obj = {
    sthg: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.ResNested}
 */
proto.relay.onboarding.v1.ResNested.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.ResNested;
  return proto.relay.onboarding.v1.ResNested.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.ResNested} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.ResNested}
 */
proto.relay.onboarding.v1.ResNested.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSthg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.ResNested.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.ResNested.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.ResNested} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.ResNested.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSthg();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string Sthg = 1;
 * @return {string}
 */
proto.relay.onboarding.v1.ResNested.prototype.getSthg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.ResNested} returns this
 */
proto.relay.onboarding.v1.ResNested.prototype.setSthg = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.relay.onboarding.v1.CompletelyNew.oneofGroups_ = [[3,4,6,7]];

/**
 * @enum {number}
 */
proto.relay.onboarding.v1.CompletelyNew.PaymentselectionCase = {
  PAYMENTSELECTION_NOT_SET: 0,
  INITREQ: 3,
  INITRES: 4,
  PAYMET: 6,
  PAYMENT_METHOD: 7
};

/**
 * @return {proto.relay.onboarding.v1.CompletelyNew.PaymentselectionCase}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.getPaymentselectionCase = function() {
  return /** @type {proto.relay.onboarding.v1.CompletelyNew.PaymentselectionCase} */(jspb.Message.computeOneofCase(this, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.CompletelyNew.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.CompletelyNew} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.CompletelyNew.toObject = function(includeInstance, msg) {
  var f, obj = {
    description: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tryNested: (f = msg.getTryNested()) && proto.relay.onboarding.v1.TryNested.toObject(includeInstance, f),
    initreq: jspb.Message.getFieldWithDefault(msg, 3, ""),
    initres: jspb.Message.getFieldWithDefault(msg, 4, ""),
    paymet: (f = msg.getPaymet()) && relay_onboarding_v1_paymentmethods_ppro_pb.BusinessDetails.toObject(includeInstance, f),
    paymentMethod: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.CompletelyNew}
 */
proto.relay.onboarding.v1.CompletelyNew.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.CompletelyNew;
  return proto.relay.onboarding.v1.CompletelyNew.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.CompletelyNew} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.CompletelyNew}
 */
proto.relay.onboarding.v1.CompletelyNew.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 2:
      var value = new proto.relay.onboarding.v1.TryNested;
      reader.readMessage(value,proto.relay.onboarding.v1.TryNested.deserializeBinaryFromReader);
      msg.setTryNested(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInitreq(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setInitres(value);
      break;
    case 6:
      var value = new relay_onboarding_v1_paymentmethods_ppro_pb.BusinessDetails;
      reader.readMessage(value,relay_onboarding_v1_paymentmethods_ppro_pb.BusinessDetails.deserializeBinaryFromReader);
      msg.setPaymet(value);
      break;
    case 7:
      var value = /** @type {!proto.relay.PaymentMethod} */ (reader.readEnum());
      msg.setPaymentMethod(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.CompletelyNew.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.CompletelyNew} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.CompletelyNew.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTryNested();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.relay.onboarding.v1.TryNested.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPaymet();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      relay_onboarding_v1_paymentmethods_ppro_pb.BusinessDetails.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.relay.PaymentMethod} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional string description = 1;
 * @return {string}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TryNested try_nested = 2;
 * @return {?proto.relay.onboarding.v1.TryNested}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.getTryNested = function() {
  return /** @type{?proto.relay.onboarding.v1.TryNested} */ (
    jspb.Message.getWrapperField(this, proto.relay.onboarding.v1.TryNested, 2));
};


/**
 * @param {?proto.relay.onboarding.v1.TryNested|undefined} value
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
*/
proto.relay.onboarding.v1.CompletelyNew.prototype.setTryNested = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.clearTryNested = function() {
  return this.setTryNested(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.hasTryNested = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string InitReq = 3;
 * @return {string}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.getInitreq = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.setInitreq = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.clearInitreq = function() {
  return jspb.Message.setOneofField(this, 3, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.hasInitreq = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string InitRes = 4;
 * @return {string}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.getInitres = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.setInitres = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.clearInitres = function() {
  return jspb.Message.setOneofField(this, 4, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.hasInitres = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional paymentmethods.ppro.BusinessDetails paymet = 6;
 * @return {?proto.relay.onboarding.v1.paymentmethods.ppro.BusinessDetails}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.getPaymet = function() {
  return /** @type{?proto.relay.onboarding.v1.paymentmethods.ppro.BusinessDetails} */ (
    jspb.Message.getWrapperField(this, relay_onboarding_v1_paymentmethods_ppro_pb.BusinessDetails, 6));
};


/**
 * @param {?proto.relay.onboarding.v1.paymentmethods.ppro.BusinessDetails|undefined} value
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
*/
proto.relay.onboarding.v1.CompletelyNew.prototype.setPaymet = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.clearPaymet = function() {
  return this.setPaymet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.hasPaymet = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional relay.PaymentMethod payment_method = 7;
 * @return {!proto.relay.PaymentMethod}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.getPaymentMethod = function() {
  return /** @type {!proto.relay.PaymentMethod} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.relay.PaymentMethod} value
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.setPaymentMethod = function(value) {
  return jspb.Message.setOneofField(this, 7, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.relay.onboarding.v1.CompletelyNew} returns this
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.clearPaymentMethod = function() {
  return jspb.Message.setOneofField(this, 7, proto.relay.onboarding.v1.CompletelyNew.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.CompletelyNew.prototype.hasPaymentMethod = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.NewIndeed.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.NewIndeed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.NewIndeed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.NewIndeed.toObject = function(includeInstance, msg) {
  var f, obj = {
    description: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.NewIndeed}
 */
proto.relay.onboarding.v1.NewIndeed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.NewIndeed;
  return proto.relay.onboarding.v1.NewIndeed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.NewIndeed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.NewIndeed}
 */
proto.relay.onboarding.v1.NewIndeed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.NewIndeed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.NewIndeed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.NewIndeed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.NewIndeed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string description = 1;
 * @return {string}
 */
proto.relay.onboarding.v1.NewIndeed.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.NewIndeed} returns this
 */
proto.relay.onboarding.v1.NewIndeed.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.InitializeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.InitializeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.InitializeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    reference: jspb.Message.getFieldWithDefault(msg, 1, ""),
    paymentMethod: jspb.Message.getFieldWithDefault(msg, 2, 0),
    data: (f = msg.getData()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.InitializeRequest}
 */
proto.relay.onboarding.v1.InitializeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.InitializeRequest;
  return proto.relay.onboarding.v1.InitializeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.InitializeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.InitializeRequest}
 */
proto.relay.onboarding.v1.InitializeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setReference(value);
      break;
    case 2:
      var value = /** @type {!proto.relay.PaymentMethod} */ (reader.readEnum());
      msg.setPaymentMethod(value);
      break;
    case 100:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.InitializeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.InitializeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.InitializeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReference();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPaymentMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional string reference = 1;
 * @return {string}
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.getReference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.InitializeRequest} returns this
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.setReference = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional relay.PaymentMethod payment_method = 2;
 * @return {!proto.relay.PaymentMethod}
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.getPaymentMethod = function() {
  return /** @type {!proto.relay.PaymentMethod} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.relay.PaymentMethod} value
 * @return {!proto.relay.onboarding.v1.InitializeRequest} returns this
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.setPaymentMethod = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional google.protobuf.Any data = 100;
 * @return {?proto.google.protobuf.Any}
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 100));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.relay.onboarding.v1.InitializeRequest} returns this
*/
proto.relay.onboarding.v1.InitializeRequest.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.InitializeRequest} returns this
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.InitializeRequest.prototype.hasData = function() {
  return jspb.Message.getField(this, 100) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.InitializeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.InitializeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.InitializeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    paymentMethodConfigurationId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    data: (f = msg.getData()) && google_protobuf_any_pb.Any.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && relay_models_pb.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.InitializeResponse}
 */
proto.relay.onboarding.v1.InitializeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.InitializeResponse;
  return proto.relay.onboarding.v1.InitializeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.InitializeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.InitializeResponse}
 */
proto.relay.onboarding.v1.InitializeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPaymentMethodConfigurationId(value);
      break;
    case 100:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    case 101:
      var value = new relay_models_pb.Status;
      reader.readMessage(value,relay_models_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.InitializeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.InitializeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.InitializeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPaymentMethodConfigurationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      relay_models_pb.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional string payment_method_configuration_id = 1;
 * @return {string}
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.getPaymentMethodConfigurationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.InitializeResponse} returns this
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.setPaymentMethodConfigurationId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Any data = 100;
 * @return {?proto.google.protobuf.Any}
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 100));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.relay.onboarding.v1.InitializeResponse} returns this
*/
proto.relay.onboarding.v1.InitializeResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.InitializeResponse} returns this
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional relay.Status status = 101;
 * @return {?proto.relay.Status}
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.getStatus = function() {
  return /** @type{?proto.relay.Status} */ (
    jspb.Message.getWrapperField(this, relay_models_pb.Status, 101));
};


/**
 * @param {?proto.relay.Status|undefined} value
 * @return {!proto.relay.onboarding.v1.InitializeResponse} returns this
*/
proto.relay.onboarding.v1.InitializeResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 101, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.InitializeResponse} returns this
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.InitializeResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 101) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.UpdateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.UpdateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.UpdateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    paymentMethodConfigurationId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    paymentMethod: jspb.Message.getFieldWithDefault(msg, 2, 0),
    data: (f = msg.getData()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.UpdateRequest}
 */
proto.relay.onboarding.v1.UpdateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.UpdateRequest;
  return proto.relay.onboarding.v1.UpdateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.UpdateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.UpdateRequest}
 */
proto.relay.onboarding.v1.UpdateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPaymentMethodConfigurationId(value);
      break;
    case 2:
      var value = /** @type {!proto.relay.PaymentMethod} */ (reader.readEnum());
      msg.setPaymentMethod(value);
      break;
    case 100:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.UpdateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.UpdateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.UpdateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPaymentMethodConfigurationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPaymentMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional string payment_method_configuration_id = 1;
 * @return {string}
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.getPaymentMethodConfigurationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.UpdateRequest} returns this
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.setPaymentMethodConfigurationId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional relay.PaymentMethod payment_method = 2;
 * @return {!proto.relay.PaymentMethod}
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.getPaymentMethod = function() {
  return /** @type {!proto.relay.PaymentMethod} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.relay.PaymentMethod} value
 * @return {!proto.relay.onboarding.v1.UpdateRequest} returns this
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.setPaymentMethod = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional google.protobuf.Any data = 100;
 * @return {?proto.google.protobuf.Any}
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 100));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.relay.onboarding.v1.UpdateRequest} returns this
*/
proto.relay.onboarding.v1.UpdateRequest.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.UpdateRequest} returns this
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.UpdateRequest.prototype.hasData = function() {
  return jspb.Message.getField(this, 100) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.UpdateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.UpdateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.UpdateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.UpdateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && google_protobuf_any_pb.Any.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && relay_models_pb.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.UpdateResponse}
 */
proto.relay.onboarding.v1.UpdateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.UpdateResponse;
  return proto.relay.onboarding.v1.UpdateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.UpdateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.UpdateResponse}
 */
proto.relay.onboarding.v1.UpdateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 100:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    case 101:
      var value = new relay_models_pb.Status;
      reader.readMessage(value,relay_models_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.UpdateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.UpdateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.UpdateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.UpdateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      relay_models_pb.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Any data = 100;
 * @return {?proto.google.protobuf.Any}
 */
proto.relay.onboarding.v1.UpdateResponse.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 100));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.relay.onboarding.v1.UpdateResponse} returns this
*/
proto.relay.onboarding.v1.UpdateResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.UpdateResponse} returns this
 */
proto.relay.onboarding.v1.UpdateResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.UpdateResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional relay.Status status = 101;
 * @return {?proto.relay.Status}
 */
proto.relay.onboarding.v1.UpdateResponse.prototype.getStatus = function() {
  return /** @type{?proto.relay.Status} */ (
    jspb.Message.getWrapperField(this, relay_models_pb.Status, 101));
};


/**
 * @param {?proto.relay.Status|undefined} value
 * @return {!proto.relay.onboarding.v1.UpdateResponse} returns this
*/
proto.relay.onboarding.v1.UpdateResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 101, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.UpdateResponse} returns this
 */
proto.relay.onboarding.v1.UpdateResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.UpdateResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 101) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.GetRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.GetRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.GetRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.GetRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    paymentMethodConfigurationId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    paymentMethod: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.GetRequest}
 */
proto.relay.onboarding.v1.GetRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.GetRequest;
  return proto.relay.onboarding.v1.GetRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.GetRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.GetRequest}
 */
proto.relay.onboarding.v1.GetRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPaymentMethodConfigurationId(value);
      break;
    case 2:
      var value = /** @type {!proto.relay.PaymentMethod} */ (reader.readEnum());
      msg.setPaymentMethod(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.GetRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.GetRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.GetRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.GetRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPaymentMethodConfigurationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPaymentMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string payment_method_configuration_id = 1;
 * @return {string}
 */
proto.relay.onboarding.v1.GetRequest.prototype.getPaymentMethodConfigurationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.GetRequest} returns this
 */
proto.relay.onboarding.v1.GetRequest.prototype.setPaymentMethodConfigurationId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional relay.PaymentMethod payment_method = 2;
 * @return {!proto.relay.PaymentMethod}
 */
proto.relay.onboarding.v1.GetRequest.prototype.getPaymentMethod = function() {
  return /** @type {!proto.relay.PaymentMethod} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.relay.PaymentMethod} value
 * @return {!proto.relay.onboarding.v1.GetRequest} returns this
 */
proto.relay.onboarding.v1.GetRequest.prototype.setPaymentMethod = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.GetResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.GetResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.GetResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.GetResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    paymentMethodOnboardingStatus: jspb.Message.getFieldWithDefault(msg, 1, 0),
    data: (f = msg.getData()) && google_protobuf_any_pb.Any.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && relay_models_pb.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.GetResponse}
 */
proto.relay.onboarding.v1.GetResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.GetResponse;
  return proto.relay.onboarding.v1.GetResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.GetResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.GetResponse}
 */
proto.relay.onboarding.v1.GetResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.relay.onboarding.v1.PaymentMethodOnboardingStatus} */ (reader.readEnum());
      msg.setPaymentMethodOnboardingStatus(value);
      break;
    case 100:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    case 101:
      var value = new relay_models_pb.Status;
      reader.readMessage(value,relay_models_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.GetResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.GetResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.GetResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.GetResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPaymentMethodOnboardingStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      relay_models_pb.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional PaymentMethodOnboardingStatus payment_method_onboarding_status = 1;
 * @return {!proto.relay.onboarding.v1.PaymentMethodOnboardingStatus}
 */
proto.relay.onboarding.v1.GetResponse.prototype.getPaymentMethodOnboardingStatus = function() {
  return /** @type {!proto.relay.onboarding.v1.PaymentMethodOnboardingStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.relay.onboarding.v1.PaymentMethodOnboardingStatus} value
 * @return {!proto.relay.onboarding.v1.GetResponse} returns this
 */
proto.relay.onboarding.v1.GetResponse.prototype.setPaymentMethodOnboardingStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional google.protobuf.Any data = 100;
 * @return {?proto.google.protobuf.Any}
 */
proto.relay.onboarding.v1.GetResponse.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 100));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.relay.onboarding.v1.GetResponse} returns this
*/
proto.relay.onboarding.v1.GetResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.GetResponse} returns this
 */
proto.relay.onboarding.v1.GetResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.GetResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional relay.Status status = 101;
 * @return {?proto.relay.Status}
 */
proto.relay.onboarding.v1.GetResponse.prototype.getStatus = function() {
  return /** @type{?proto.relay.Status} */ (
    jspb.Message.getWrapperField(this, relay_models_pb.Status, 101));
};


/**
 * @param {?proto.relay.Status|undefined} value
 * @return {!proto.relay.onboarding.v1.GetResponse} returns this
*/
proto.relay.onboarding.v1.GetResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 101, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.GetResponse} returns this
 */
proto.relay.onboarding.v1.GetResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.GetResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * @enum {number}
 */
proto.relay.onboarding.v1.PaymentMethodOnboardingStatus = {
  PENDING: 0,
  ACTIVATED: 1,
  NON_COMPLIANT: 2,
  DEACTIVATED: 3,
  TERMINATED: 4
};

goog.object.extend(exports, proto.relay.onboarding.v1);
