/* eslint-disable */
/*Generated by GenDocu.com*/
// package: relay.onboarding.v1
// file: relay/onboarding/v1/payment_method_onboarding_service.proto

import * as relay_onboarding_v1_payment_method_onboarding_service_pb from "../../../relay/onboarding/v1/payment_method_onboarding_service_pb";
import {grpc} from "@improbable-eng/grpc-web";

type PaymentMethodOnboardingInitialize = {
  readonly methodName: string;
  readonly service: typeof PaymentMethodOnboarding;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.InitializeRequest;
  readonly responseType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.InitializeResponse;
};

type PaymentMethodOnboardingUpdate = {
  readonly methodName: string;
  readonly service: typeof PaymentMethodOnboarding;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.UpdateRequest;
  readonly responseType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.UpdateResponse;
};

type PaymentMethodOnboardingGet = {
  readonly methodName: string;
  readonly service: typeof PaymentMethodOnboarding;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.GetRequest;
  readonly responseType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.GetResponse;
};

type PaymentMethodOnboardingNew = {
  readonly methodName: string;
  readonly service: typeof PaymentMethodOnboarding;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.CompletelyNew;
  readonly responseType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.NewIndeed;
};

type PaymentMethodOnboardingNested = {
  readonly methodName: string;
  readonly service: typeof PaymentMethodOnboarding;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.TryNested;
  readonly responseType: typeof relay_onboarding_v1_payment_method_onboarding_service_pb.ResNested;
};

export class PaymentMethodOnboarding {
  static readonly serviceName: string;
  static readonly Initialize: PaymentMethodOnboardingInitialize;
  static readonly Update: PaymentMethodOnboardingUpdate;
  static readonly Get: PaymentMethodOnboardingGet;
  static readonly New: PaymentMethodOnboardingNew;
  static readonly Nested: PaymentMethodOnboardingNested;
}

export type ServiceError = { message: string, code: number; metadata: grpc.Metadata }
export type Status = { details: string, code: number; metadata: grpc.Metadata }

interface UnaryResponse {
  cancel(): void;
}
interface ResponseStream<T> {
  cancel(): void;
  on(type: 'data', handler: (message: T) => void): ResponseStream<T>;
  on(type: 'end', handler: (status?: Status) => void): ResponseStream<T>;
  on(type: 'status', handler: (status: Status) => void): ResponseStream<T>;
}
interface RequestStream<T> {
  write(message: T): RequestStream<T>;
  end(): void;
  cancel(): void;
  on(type: 'end', handler: (status?: Status) => void): RequestStream<T>;
  on(type: 'status', handler: (status: Status) => void): RequestStream<T>;
}
interface BidirectionalStream<ReqT, ResT> {
  write(message: ReqT): BidirectionalStream<ReqT, ResT>;
  end(): void;
  cancel(): void;
  on(type: 'data', handler: (message: ResT) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'end', handler: (status?: Status) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'status', handler: (status: Status) => void): BidirectionalStream<ReqT, ResT>;
}

export class PaymentMethodOnboardingClient {
  readonly serviceHost: string;

  constructor(serviceHost: string, options?: grpc.RpcOptions);
  initialize(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.InitializeRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.InitializeResponse|null) => void
  ): UnaryResponse;
  initialize(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.InitializeRequest,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.InitializeResponse|null) => void
  ): UnaryResponse;
  update(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.UpdateRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.UpdateResponse|null) => void
  ): UnaryResponse;
  update(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.UpdateRequest,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.UpdateResponse|null) => void
  ): UnaryResponse;
  get(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.GetRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.GetResponse|null) => void
  ): UnaryResponse;
  get(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.GetRequest,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.GetResponse|null) => void
  ): UnaryResponse;
  new(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.CompletelyNew,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.NewIndeed|null) => void
  ): UnaryResponse;
  new(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.CompletelyNew,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.NewIndeed|null) => void
  ): UnaryResponse;
  nested(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.TryNested,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.ResNested|null) => void
  ): UnaryResponse;
  nested(
    requestMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.TryNested,
    callback: (error: ServiceError|null, responseMessage: relay_onboarding_v1_payment_method_onboarding_service_pb.ResNested|null) => void
  ): UnaryResponse;
}

