/* eslint-disable */
/*Generated by GenDocu.com*/
// package: relay.onboarding.v1
// file: relay/onboarding/v1/payment_method_onboarding_service.proto

import * as jspb from "google-protobuf";
import * as google_protobuf_any_pb from "google-protobuf/google/protobuf/any_pb";
import * as relay_models_pb from "../../../relay/models_pb";
import * as relay_onboarding_v1_paymentmethods_ppro_pb from "../../../relay/onboarding/v1/paymentmethods/ppro_pb";

export class TryNested extends jspb.Message {
  getSthg(): string;
  setSthg(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): TryNested.AsObject;
  static toObject(includeInstance: boolean, msg: TryNested): TryNested.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: TryNested, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): TryNested;
  static deserializeBinaryFromReader(message: TryNested, reader: jspb.BinaryReader): TryNested;
}

export namespace TryNested {
  export type AsObject = {
    sthg: string,
  }
}

export class ResNested extends jspb.Message {
  getSthg(): string;
  setSthg(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): ResNested.AsObject;
  static toObject(includeInstance: boolean, msg: ResNested): ResNested.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: ResNested, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): ResNested;
  static deserializeBinaryFromReader(message: ResNested, reader: jspb.BinaryReader): ResNested;
}

export namespace ResNested {
  export type AsObject = {
    sthg: string,
  }
}

export class CompletelyNew extends jspb.Message {
  getDescription(): string;
  setDescription(value: string): void;

  hasTryNested(): boolean;
  clearTryNested(): void;
  getTryNested(): TryNested | undefined;
  setTryNested(value?: TryNested): void;

  hasInitreq(): boolean;
  clearInitreq(): void;
  getInitreq(): string;
  setInitreq(value: string): void;

  hasInitres(): boolean;
  clearInitres(): void;
  getInitres(): string;
  setInitres(value: string): void;

  hasPaymet(): boolean;
  clearPaymet(): void;
  getPaymet(): relay_onboarding_v1_paymentmethods_ppro_pb.BusinessDetails | undefined;
  setPaymet(value?: relay_onboarding_v1_paymentmethods_ppro_pb.BusinessDetails): void;

  hasPaymentMethod(): boolean;
  clearPaymentMethod(): void;
  getPaymentMethod(): relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap];
  setPaymentMethod(value: relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap]): void;

  getPaymentselectionCase(): CompletelyNew.PaymentselectionCase;
  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): CompletelyNew.AsObject;
  static toObject(includeInstance: boolean, msg: CompletelyNew): CompletelyNew.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: CompletelyNew, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): CompletelyNew;
  static deserializeBinaryFromReader(message: CompletelyNew, reader: jspb.BinaryReader): CompletelyNew;
}

export namespace CompletelyNew {
  export type AsObject = {
    description: string,
    tryNested?: TryNested.AsObject,
    initreq: string,
    initres: string,
    paymet?: relay_onboarding_v1_paymentmethods_ppro_pb.BusinessDetails.AsObject,
    paymentMethod: relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap],
  }

  export enum PaymentselectionCase {
    PAYMENTSELECTION_NOT_SET = 0,
    INITREQ = 3,
    INITRES = 4,
    PAYMET = 6,
    PAYMENT_METHOD = 7,
  }
}

export class NewIndeed extends jspb.Message {
  getDescription(): string;
  setDescription(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): NewIndeed.AsObject;
  static toObject(includeInstance: boolean, msg: NewIndeed): NewIndeed.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: NewIndeed, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): NewIndeed;
  static deserializeBinaryFromReader(message: NewIndeed, reader: jspb.BinaryReader): NewIndeed;
}

export namespace NewIndeed {
  export type AsObject = {
    description: string,
  }
}

export class InitializeRequest extends jspb.Message {
  getReference(): string;
  setReference(value: string): void;

  getPaymentMethod(): relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap];
  setPaymentMethod(value: relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap]): void;

  hasData(): boolean;
  clearData(): void;
  getData(): google_protobuf_any_pb.Any | undefined;
  setData(value?: google_protobuf_any_pb.Any): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): InitializeRequest.AsObject;
  static toObject(includeInstance: boolean, msg: InitializeRequest): InitializeRequest.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: InitializeRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): InitializeRequest;
  static deserializeBinaryFromReader(message: InitializeRequest, reader: jspb.BinaryReader): InitializeRequest;
}

export namespace InitializeRequest {
  export type AsObject = {
    reference: string,
    paymentMethod: relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap],
    data?: google_protobuf_any_pb.Any.AsObject,
  }
}

export class InitializeResponse extends jspb.Message {
  getPaymentMethodConfigurationId(): string;
  setPaymentMethodConfigurationId(value: string): void;

  hasData(): boolean;
  clearData(): void;
  getData(): google_protobuf_any_pb.Any | undefined;
  setData(value?: google_protobuf_any_pb.Any): void;

  hasStatus(): boolean;
  clearStatus(): void;
  getStatus(): relay_models_pb.Status | undefined;
  setStatus(value?: relay_models_pb.Status): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): InitializeResponse.AsObject;
  static toObject(includeInstance: boolean, msg: InitializeResponse): InitializeResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: InitializeResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): InitializeResponse;
  static deserializeBinaryFromReader(message: InitializeResponse, reader: jspb.BinaryReader): InitializeResponse;
}

export namespace InitializeResponse {
  export type AsObject = {
    paymentMethodConfigurationId: string,
    data?: google_protobuf_any_pb.Any.AsObject,
    status?: relay_models_pb.Status.AsObject,
  }
}

export class UpdateRequest extends jspb.Message {
  getPaymentMethodConfigurationId(): string;
  setPaymentMethodConfigurationId(value: string): void;

  getPaymentMethod(): relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap];
  setPaymentMethod(value: relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap]): void;

  hasData(): boolean;
  clearData(): void;
  getData(): google_protobuf_any_pb.Any | undefined;
  setData(value?: google_protobuf_any_pb.Any): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): UpdateRequest.AsObject;
  static toObject(includeInstance: boolean, msg: UpdateRequest): UpdateRequest.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: UpdateRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): UpdateRequest;
  static deserializeBinaryFromReader(message: UpdateRequest, reader: jspb.BinaryReader): UpdateRequest;
}

export namespace UpdateRequest {
  export type AsObject = {
    paymentMethodConfigurationId: string,
    paymentMethod: relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap],
    data?: google_protobuf_any_pb.Any.AsObject,
  }
}

export class UpdateResponse extends jspb.Message {
  hasData(): boolean;
  clearData(): void;
  getData(): google_protobuf_any_pb.Any | undefined;
  setData(value?: google_protobuf_any_pb.Any): void;

  hasStatus(): boolean;
  clearStatus(): void;
  getStatus(): relay_models_pb.Status | undefined;
  setStatus(value?: relay_models_pb.Status): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): UpdateResponse.AsObject;
  static toObject(includeInstance: boolean, msg: UpdateResponse): UpdateResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: UpdateResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): UpdateResponse;
  static deserializeBinaryFromReader(message: UpdateResponse, reader: jspb.BinaryReader): UpdateResponse;
}

export namespace UpdateResponse {
  export type AsObject = {
    data?: google_protobuf_any_pb.Any.AsObject,
    status?: relay_models_pb.Status.AsObject,
  }
}

export class GetRequest extends jspb.Message {
  getPaymentMethodConfigurationId(): string;
  setPaymentMethodConfigurationId(value: string): void;

  getPaymentMethod(): relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap];
  setPaymentMethod(value: relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap]): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): GetRequest.AsObject;
  static toObject(includeInstance: boolean, msg: GetRequest): GetRequest.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: GetRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): GetRequest;
  static deserializeBinaryFromReader(message: GetRequest, reader: jspb.BinaryReader): GetRequest;
}

export namespace GetRequest {
  export type AsObject = {
    paymentMethodConfigurationId: string,
    paymentMethod: relay_models_pb.PaymentMethodMap[keyof relay_models_pb.PaymentMethodMap],
  }
}

export class GetResponse extends jspb.Message {
  getPaymentMethodOnboardingStatus(): PaymentMethodOnboardingStatusMap[keyof PaymentMethodOnboardingStatusMap];
  setPaymentMethodOnboardingStatus(value: PaymentMethodOnboardingStatusMap[keyof PaymentMethodOnboardingStatusMap]): void;

  hasData(): boolean;
  clearData(): void;
  getData(): google_protobuf_any_pb.Any | undefined;
  setData(value?: google_protobuf_any_pb.Any): void;

  hasStatus(): boolean;
  clearStatus(): void;
  getStatus(): relay_models_pb.Status | undefined;
  setStatus(value?: relay_models_pb.Status): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): GetResponse.AsObject;
  static toObject(includeInstance: boolean, msg: GetResponse): GetResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: GetResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): GetResponse;
  static deserializeBinaryFromReader(message: GetResponse, reader: jspb.BinaryReader): GetResponse;
}

export namespace GetResponse {
  export type AsObject = {
    paymentMethodOnboardingStatus: PaymentMethodOnboardingStatusMap[keyof PaymentMethodOnboardingStatusMap],
    data?: google_protobuf_any_pb.Any.AsObject,
    status?: relay_models_pb.Status.AsObject,
  }
}

export interface PaymentMethodOnboardingStatusMap {
  PENDING: 0;
  ACTIVATED: 1;
  NON_COMPLIANT: 2;
  DEACTIVATED: 3;
  TERMINATED: 4;
}

export const PaymentMethodOnboardingStatus: PaymentMethodOnboardingStatusMap;

