// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: relay/processing/v1/paymentmethods/ppro/sofort.proto

package ppro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargeRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentFlowData *PaymentFlowRedirectRequestData `protobuf:"bytes,1,opt,name=payment_flow_data,json=paymentFlowData,proto3" json:"payment_flow_data,omitempty"`
	Consumer        *Consumer                       `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
}

func (x *ChargeRequestData) Reset() {
	*x = ChargeRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequestData) ProtoMessage() {}

func (x *ChargeRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequestData.ProtoReflect.Descriptor instead.
func (*ChargeRequestData) Descriptor() ([]byte, []int) {
	return file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescGZIP(), []int{0}
}

func (x *ChargeRequestData) GetPaymentFlowData() *PaymentFlowRedirectRequestData {
	if x != nil {
		return x.PaymentFlowData
	}
	return nil
}

func (x *ChargeRequestData) GetConsumer() *Consumer {
	if x != nil {
		return x.Consumer
	}
	return nil
}

type ChargeResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentFlowData *PaymentFlowRedirectResponseData `protobuf:"bytes,1,opt,name=payment_flow_data,json=paymentFlowData,proto3" json:"payment_flow_data,omitempty"`
}

func (x *ChargeResponseData) Reset() {
	*x = ChargeResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeResponseData) ProtoMessage() {}

func (x *ChargeResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeResponseData.ProtoReflect.Descriptor instead.
func (*ChargeResponseData) Descriptor() ([]byte, []int) {
	return file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescGZIP(), []int{1}
}

func (x *ChargeResponseData) GetPaymentFlowData() *PaymentFlowRedirectResponseData {
	if x != nil {
		return x.PaymentFlowData
	}
	return nil
}

type Consumer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Format: ISO 3166-1 alpha-3, e.g. NOR, SWE, DNK
	CountryCode string `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
}

func (x *Consumer) Reset() {
	*x = Consumer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumer) ProtoMessage() {}

func (x *Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumer.ProtoReflect.Descriptor instead.
func (*Consumer) Descriptor() ([]byte, []int) {
	return file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescGZIP(), []int{2}
}

func (x *Consumer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Consumer) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type PaymentFlowRedirectRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// PaymentId and ChargeId are appended as query parameters
	SuccessUrl string `protobuf:"bytes,1,opt,name=success_url,json=successUrl,proto3" json:"success_url,omitempty"`
	// PaymentId and ChargeId are appended as query parameters
	FailedUrl string `protobuf:"bytes,2,opt,name=failed_url,json=failedUrl,proto3" json:"failed_url,omitempty"`
	// PaymentId and ChargeId are appended as query parameters
	CancelUrl string `protobuf:"bytes,3,opt,name=cancel_url,json=cancelUrl,proto3" json:"cancel_url,omitempty"`
}

func (x *PaymentFlowRedirectRequestData) Reset() {
	*x = PaymentFlowRedirectRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentFlowRedirectRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFlowRedirectRequestData) ProtoMessage() {}

func (x *PaymentFlowRedirectRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFlowRedirectRequestData.ProtoReflect.Descriptor instead.
func (*PaymentFlowRedirectRequestData) Descriptor() ([]byte, []int) {
	return file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentFlowRedirectRequestData) GetSuccessUrl() string {
	if x != nil {
		return x.SuccessUrl
	}
	return ""
}

func (x *PaymentFlowRedirectRequestData) GetFailedUrl() string {
	if x != nil {
		return x.FailedUrl
	}
	return ""
}

func (x *PaymentFlowRedirectRequestData) GetCancelUrl() string {
	if x != nil {
		return x.CancelUrl
	}
	return ""
}

type PaymentFlowRedirectResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApprovalUrl string `protobuf:"bytes,1,opt,name=approval_url,json=approvalUrl,proto3" json:"approval_url,omitempty"`
}

func (x *PaymentFlowRedirectResponseData) Reset() {
	*x = PaymentFlowRedirectResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentFlowRedirectResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFlowRedirectResponseData) ProtoMessage() {}

func (x *PaymentFlowRedirectResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFlowRedirectResponseData.ProtoReflect.Descriptor instead.
func (*PaymentFlowRedirectResponseData) Descriptor() ([]byte, []int) {
	return file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentFlowRedirectResponseData) GetApprovalUrl() string {
	if x != nil {
		return x.ApprovalUrl
	}
	return ""
}

var File_relay_processing_v1_paymentmethods_ppro_sofort_proto protoreflect.FileDescriptor

var file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDesc = []byte{
	0x0a, 0x34, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x73, 0x2f, 0x70, 0x70, 0x72, 0x6f, 0x2f, 0x73, 0x6f, 0x66, 0x6f, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x70, 0x72, 0x6f, 0x2e,
	0x73, 0x6f, 0x66, 0x6f, 0x72, 0x74, 0x22, 0xe5, 0x01, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x7a, 0x0a, 0x11,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4e, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x70, 0x72,
	0x6f, 0x2e, 0x73, 0x6f, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x46, 0x6c, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x61, 0x12, 0x54, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x2e,
	0x70, 0x70, 0x72, 0x6f, 0x2e, 0x73, 0x6f, 0x66, 0x6f, 0x72, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x22, 0x91,
	0x01, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x7b, 0x0a, 0x11, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x4f, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x70, 0x72, 0x6f, 0x2e, 0x73, 0x6f, 0x66, 0x6f, 0x72,
	0x74, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x41, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x7f, 0x0a, 0x1e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x44, 0x0a, 0x1f, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x42, 0x86, 0x01, 0x5a,
	0x53, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x65, 0x64, 0x76,
	0x65, 0x64, 0x37, 0x35, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6f, 0x6e, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x2f,
	0x70, 0x70, 0x72, 0x6f, 0xaa, 0x02, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x2e, 0x56, 0x31, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x2e, 0x50, 0x70, 0x72, 0x6f, 0x2e, 0x53,
	0x6f, 0x66, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescOnce sync.Once
	file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescData = file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDesc
)

func file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescGZIP() []byte {
	file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescOnce.Do(func() {
		file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescData = protoimpl.X.CompressGZIP(file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescData)
	})
	return file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDescData
}

var file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_relay_processing_v1_paymentmethods_ppro_sofort_proto_goTypes = []interface{}{
	(*ChargeRequestData)(nil),               // 0: relay.processing.v1.paymentmethods.ppro.sofort.ChargeRequestData
	(*ChargeResponseData)(nil),              // 1: relay.processing.v1.paymentmethods.ppro.sofort.ChargeResponseData
	(*Consumer)(nil),                        // 2: relay.processing.v1.paymentmethods.ppro.sofort.Consumer
	(*PaymentFlowRedirectRequestData)(nil),  // 3: relay.processing.v1.paymentmethods.ppro.sofort.PaymentFlowRedirectRequestData
	(*PaymentFlowRedirectResponseData)(nil), // 4: relay.processing.v1.paymentmethods.ppro.sofort.PaymentFlowRedirectResponseData
}
var file_relay_processing_v1_paymentmethods_ppro_sofort_proto_depIdxs = []int32{
	3, // 0: relay.processing.v1.paymentmethods.ppro.sofort.ChargeRequestData.payment_flow_data:type_name -> relay.processing.v1.paymentmethods.ppro.sofort.PaymentFlowRedirectRequestData
	2, // 1: relay.processing.v1.paymentmethods.ppro.sofort.ChargeRequestData.consumer:type_name -> relay.processing.v1.paymentmethods.ppro.sofort.Consumer
	4, // 2: relay.processing.v1.paymentmethods.ppro.sofort.ChargeResponseData.payment_flow_data:type_name -> relay.processing.v1.paymentmethods.ppro.sofort.PaymentFlowRedirectResponseData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_relay_processing_v1_paymentmethods_ppro_sofort_proto_init() }
func file_relay_processing_v1_paymentmethods_ppro_sofort_proto_init() {
	if File_relay_processing_v1_paymentmethods_ppro_sofort_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargeRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChargeResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consumer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentFlowRedirectRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentFlowRedirectResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_processing_v1_paymentmethods_ppro_sofort_proto_goTypes,
		DependencyIndexes: file_relay_processing_v1_paymentmethods_ppro_sofort_proto_depIdxs,
		MessageInfos:      file_relay_processing_v1_paymentmethods_ppro_sofort_proto_msgTypes,
	}.Build()
	File_relay_processing_v1_paymentmethods_ppro_sofort_proto = out.File
	file_relay_processing_v1_paymentmethods_ppro_sofort_proto_rawDesc = nil
	file_relay_processing_v1_paymentmethods_ppro_sofort_proto_goTypes = nil
	file_relay_processing_v1_paymentmethods_ppro_sofort_proto_depIdxs = nil
}
