/* eslint-disable */
/*Generated by GenDocu.com*/
// package: relay.notification.v1
// file: relay/notification/v1/notification_configuration_service.proto

import * as jspb from "google-protobuf";
import * as google_protobuf_any_pb from "google-protobuf/google/protobuf/any_pb";
import * as relay_models_pb from "../../../relay/models_pb";

export class CreateWebhookConfigurationRequest extends jspb.Message {
  getRequestId(): string;
  setRequestId(value: string): void;

  clearEventsList(): void;
  getEventsList(): Array<string>;
  setEventsList(value: Array<string>): void;
  addEvents(value: string, index?: number): string;

  getUrl(): string;
  setUrl(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): CreateWebhookConfigurationRequest.AsObject;
  static toObject(includeInstance: boolean, msg: CreateWebhookConfigurationRequest): CreateWebhookConfigurationRequest.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: CreateWebhookConfigurationRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): CreateWebhookConfigurationRequest;
  static deserializeBinaryFromReader(message: CreateWebhookConfigurationRequest, reader: jspb.BinaryReader): CreateWebhookConfigurationRequest;
}

export namespace CreateWebhookConfigurationRequest {
  export type AsObject = {
    requestId: string,
    eventsList: Array<string>,
    url: string,
  }
}

export class CreateWebhookConfigurationResponse extends jspb.Message {
  getNotificationConfigurationId(): string;
  setNotificationConfigurationId(value: string): void;

  hasStatus(): boolean;
  clearStatus(): void;
  getStatus(): relay_models_pb.Status | undefined;
  setStatus(value?: relay_models_pb.Status): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): CreateWebhookConfigurationResponse.AsObject;
  static toObject(includeInstance: boolean, msg: CreateWebhookConfigurationResponse): CreateWebhookConfigurationResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: CreateWebhookConfigurationResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): CreateWebhookConfigurationResponse;
  static deserializeBinaryFromReader(message: CreateWebhookConfigurationResponse, reader: jspb.BinaryReader): CreateWebhookConfigurationResponse;
}

export namespace CreateWebhookConfigurationResponse {
  export type AsObject = {
    notificationConfigurationId: string,
    status?: relay_models_pb.Status.AsObject,
  }
}

export class GetConfigurationRequest extends jspb.Message {
  getNotificationConfigurationId(): string;
  setNotificationConfigurationId(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): GetConfigurationRequest.AsObject;
  static toObject(includeInstance: boolean, msg: GetConfigurationRequest): GetConfigurationRequest.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: GetConfigurationRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): GetConfigurationRequest;
  static deserializeBinaryFromReader(message: GetConfigurationRequest, reader: jspb.BinaryReader): GetConfigurationRequest;
}

export namespace GetConfigurationRequest {
  export type AsObject = {
    notificationConfigurationId: string,
  }
}

export class GetConfigurationResponse extends jspb.Message {
  clearEventsList(): void;
  getEventsList(): Array<string>;
  setEventsList(value: Array<string>): void;
  addEvents(value: string, index?: number): string;

  hasData(): boolean;
  clearData(): void;
  getData(): google_protobuf_any_pb.Any | undefined;
  setData(value?: google_protobuf_any_pb.Any): void;

  hasStatus(): boolean;
  clearStatus(): void;
  getStatus(): relay_models_pb.Status | undefined;
  setStatus(value?: relay_models_pb.Status): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): GetConfigurationResponse.AsObject;
  static toObject(includeInstance: boolean, msg: GetConfigurationResponse): GetConfigurationResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: GetConfigurationResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): GetConfigurationResponse;
  static deserializeBinaryFromReader(message: GetConfigurationResponse, reader: jspb.BinaryReader): GetConfigurationResponse;
}

export namespace GetConfigurationResponse {
  export type AsObject = {
    eventsList: Array<string>,
    data?: google_protobuf_any_pb.Any.AsObject,
    status?: relay_models_pb.Status.AsObject,
  }
}

export class DeleteConfigurationRequest extends jspb.Message {
  getNotificationConfigurationId(): string;
  setNotificationConfigurationId(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): DeleteConfigurationRequest.AsObject;
  static toObject(includeInstance: boolean, msg: DeleteConfigurationRequest): DeleteConfigurationRequest.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: DeleteConfigurationRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): DeleteConfigurationRequest;
  static deserializeBinaryFromReader(message: DeleteConfigurationRequest, reader: jspb.BinaryReader): DeleteConfigurationRequest;
}

export namespace DeleteConfigurationRequest {
  export type AsObject = {
    notificationConfigurationId: string,
  }
}

export class DeleteConfigurationResponse extends jspb.Message {
  hasStatus(): boolean;
  clearStatus(): void;
  getStatus(): relay_models_pb.Status | undefined;
  setStatus(value?: relay_models_pb.Status): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): DeleteConfigurationResponse.AsObject;
  static toObject(includeInstance: boolean, msg: DeleteConfigurationResponse): DeleteConfigurationResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: DeleteConfigurationResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): DeleteConfigurationResponse;
  static deserializeBinaryFromReader(message: DeleteConfigurationResponse, reader: jspb.BinaryReader): DeleteConfigurationResponse;
}

export namespace DeleteConfigurationResponse {
  export type AsObject = {
    status?: relay_models_pb.Status.AsObject,
  }
}

